# Copyright 2016 Google LLC All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is automatically generated by CrossSync. Do not edit manually.

"""Model a set of read-only queries to a database as a snapshot."""

from typing import List
from google.cloud.spanner_v1 import PartialResultSet
from google.api_core.exceptions import InternalServerError
from google.api_core.exceptions import ServiceUnavailable
from google.api_core.exceptions import InvalidArgument
from google.cloud.spanner_v1._helpers import _augment_error_with_request_id
from google.cloud.spanner_v1._opentelemetry_tracing import trace_call
from google.cloud.spanner_v1.metrics.metrics_capture import MetricsCapture

_STREAM_RESUMPTION_INTERNAL_ERROR_MESSAGES = (
    "RST_STREAM",
    "Received unexpected EOS on DATA frame from server",
)


def _restart_on_unavailable(
    method,
    request,
    metadata=None,
    trace_name=None,
    session=None,
    attributes=None,
    transaction=None,
    transaction_selector=None,
    observability_options=None,
    request_id_manager=None,
):
    """Restart iteration after :exc:`.ServiceUnavailable`.

    :type method: callable
    :param method: function returning iterator

    :type request: proto
    :param request: request proto to call the method with

    :type transaction: :class:`google.cloud.spanner_v1.snapshot._SnapshotBase`
    :param transaction: Snapshot or Transaction class object based on the type of transaction

    :type transaction_selector: :class:`transaction_pb2.TransactionSelector`
    :param transaction_selector: Transaction selector object to be used in request if transaction is not passed,
    if both transaction_selector and transaction are passed, then transaction is given priority.
    """
    resume_token: bytes = b""
    item_buffer: List[PartialResultSet] = []
    if transaction is not None:
        transaction_selector = transaction._build_transaction_selector_pb()
    elif transaction_selector is None:
        raise InvalidArgument(
            "Either transaction or transaction_selector should be set"
        )
    request.transaction = transaction_selector
    iterator = None
    attempt = 1
    nth_request = getattr(request_id_manager, "_next_nth_request", 0)
    current_request_id = None
    while True:
        try:
            if iterator is None:
                with trace_call(
                    trace_name,
                    session,
                    attributes,
                    observability_options=observability_options,
                    metadata=metadata,
                ) as span, MetricsCapture():
                    call_metadata, current_request_id = (
                        request_id_manager.metadata_and_request_id(
                            nth_request, attempt, metadata, span
                        )
                    )
                    iterator = method(request=request, metadata=call_metadata)
            item: PartialResultSet
            for item in iterator:
                item_buffer.append(item)
                if transaction is not None:
                    transaction._update_for_result_set_pb(item)
                if (
                    item._pb is not None
                    and item._pb.HasField("precommit_token")
                    and (transaction is not None)
                ):
                    transaction._update_for_precommit_token_pb(item.precommit_token)
                if item.resume_token:
                    resume_token = item.resume_token
                    break
        except ServiceUnavailable:
            del item_buffer[:]
            request.resume_token = resume_token
            if transaction is not None:
                transaction_selector = transaction._build_transaction_selector_pb()
            request.transaction = transaction_selector
            attempt += 1
            iterator = None
            continue
        except InternalServerError as exc:
            resumable_error = any(
                (
                    resumable_message in exc.message
                    for resumable_message in _STREAM_RESUMPTION_INTERNAL_ERROR_MESSAGES
                )
            )
            if not resumable_error:
                raise _augment_error_with_request_id(exc, current_request_id)
            del item_buffer[:]
            request.resume_token = resume_token
            if transaction is not None:
                transaction_selector = transaction._build_transaction_selector_pb()
            attempt += 1
            request.transaction = transaction_selector
            iterator = None
            continue
        except Exception as exc:
            raise _augment_error_with_request_id(exc, current_request_id)
        if len(item_buffer) == 0:
            break
        for item in item_buffer:
            yield item
        del item_buffer[:]
